@baseUrl = http://127.0.0.1:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials:true

{
  "userTo": "64f6b8250f6f73f6ac7d61c3",
  "postId": "64f956b60c6a83b387997c84",
  "comment": "This is my fifth comment",
  "profilePicture": "https://res.cloudinary.com/dimejr2e8/image/upload/v1693890598/64f6b8250f6f73f6ac7d61c3"
}

###
GET {{baseUrl}}/{{urlPath}}/post/commentsnames/64f956b60c6a83b387997c84
Content-Type: application/json
Accept: application/json
withCredentials:true

###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/64f956b60c6a83b387997c84/65001c8cf6cbe9e8968cdf83
Content-Type: application/json
Accept: application/json
withCredentials:true
