@baseUrl = http://127.0.0.1:5000
@urlPath = api/v1

###
PUT {{baseUrl}}/{{urlPath}}/user/follow/64fabc02961658669b29be69
Content-Type: application/json
Accept: application/json
withCredentials:true

{}

###
PUT {{baseUrl}}/{{urlPath}}/user/unfollow/64fabc02961658669b29be69/64f6b8250f6f73f6ac7d61c3
Content-Type: application/json
Accept: application/json
withCredentials:true

{}
